<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		

<meta name="viewport" content="width=device-width, initial-scale=1">

<title>thread:[緯來] 有人跟我一樣現在緯來掛點嗎...Q.Q - JP_Entertain - 批踢踢實業坊</title>

<link rel="stylesheet" type="text/css" href="//images.ptt.cc/bbs/v2.27/bbs-common.css">
<link rel="stylesheet" type="text/css" href="//images.ptt.cc/bbs/v2.27/bbs-base.css" media="screen">
<link rel="stylesheet" type="text/css" href="//images.ptt.cc/bbs/v2.27/bbs-custom.css">
<link rel="stylesheet" type="text/css" href="//images.ptt.cc/bbs/v2.27/pushstream.css" media="screen">
<link rel="stylesheet" type="text/css" href="//images.ptt.cc/bbs/v2.27/bbs-print.css" media="print">




	<script async src='/cdn-cgi/challenge-platform/h/g/scripts/invisible.js?ts=1653454800'></script></head>
    <body>
		
<div id="topbar-container">
	<div id="topbar" class="bbs-content">
		<a id="logo" href="/bbs/">批踢踢實業坊</a>
		<span>&rsaquo;</span>
		<a class="board" href="/bbs/JP_Entertain/index.html"><span class="board-label">看板 </span>JP_Entertain</a>
		<a class="right small" href="/about.html">關於我們</a>
		<a class="right small" href="/contact.html">聯絡資訊</a>
	</div>
</div>

<div id="main-container">
	<div id="action-bar-container">
		<div class="action-bar">
			<div class="btn-group btn-group-dir">
				<a class="btn" href="/bbs/JP_Entertain/index.html">&lsaquo; 看板</a>
				<a class="btn" href="/man/JP_Entertain/index.html">精華區</a>
			</div>
			<div class="btn-group btn-group-paging">
				<a class="btn wide" href="/bbs/JP_Entertain/search?page=1&amp;q=thread%3A%5B%E7%B7%AF%E4%BE%86%5D&#43;%E6%9C%89%E4%BA%BA%E8%B7%9F%E6%88%91%E4%B8%80%E6%A8%A3%E7%8F%BE%E5%9C%A8%E7%B7%AF%E4%BE%86%E6%8E%9B%E9%BB%9E%E5%97%8E...Q.Q">最舊</a>
				<a class="btn wide disabled">&lsaquo; 上頁</a>
				<a class="btn wide disabled">下頁 &rsaquo;</a>
				<a class="btn wide" href="/bbs/JP_Entertain/search?page=1&amp;q=thread%3A%5B%E7%B7%AF%E4%BE%86%5D&#43;%E6%9C%89%E4%BA%BA%E8%B7%9F%E6%88%91%E4%B8%80%E6%A8%A3%E7%8F%BE%E5%9C%A8%E7%B7%AF%E4%BE%86%E6%8E%9B%E9%BB%9E%E5%97%8E...Q.Q">最新</a>
			</div>
		</div>
	</div>

	<div class="r-list-container action-bar-margin bbs-screen">
		<div class="search-bar">
			<form type="get" action="search" id="search-bar">
				<input class="query" type="text" name="q" value="thread:[緯來] 有人跟我一樣現在緯來掛點嗎...Q.Q" placeholder="搜尋文章&#x22ef;">
			</form>
		</div>

		
		
            
        
        
		<div class="r-ent">
			<div class="nrec"><span class="hl f2">6</span></div>
			<div class="title">
			
				<a href="/bbs/JP_Entertain/M.1263817952.A.417.html">[緯來] 有人跟我一樣現在緯來掛點嗎...Q.Q</a>
			
			</div>
			<div class="meta">
				<div class="author">ththth</div>
				<div class="article-menu">
					
					<div class="trigger">&#x22ef;</div>
					<div class="dropdown">
						<div class="item"><a href="/bbs/JP_Entertain/search?q=thread%3A%5B%E7%B7%AF%E4%BE%86%5D&#43;%E6%9C%89%E4%BA%BA%E8%B7%9F%E6%88%91%E4%B8%80%E6%A8%A3%E7%8F%BE%E5%9C%A8%E7%B7%AF%E4%BE%86%E6%8E%9B%E9%BB%9E%E5%97%8E...Q.Q">搜尋同標題文章</a></div>
						
						<div class="item"><a href="/bbs/JP_Entertain/search?q=author%3Aththth">搜尋看板內 ththth 的文章</a></div>
						
					</div>
					
				</div>
				<div class="date"> 1/18</div>
				<div class="mark"></div>
			</div>
		</div>

		
        
	</div>

    
</div>

		

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-32365737-1', {
    cookieDomain: 'ptt.cc',
    legacyCookieDomain: 'ptt.cc'
  });
  ga('send', 'pageview');
</script>


		
<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="//images.ptt.cc/bbs/v2.27/bbs.js"></script>

    <script type="text/javascript">(function(){window['__CF$cv$params']={r:'710be937afa4b005',m:'BGpPouIZGU4oJ2qh40w0p33d1HTxQuqQOOLyKn_oH0k-1653456961-0-AXzqG0Dk/v42hIHPxUJFwZLNkczJ1eADJNA5JYn8j7QYio/oTxam5B7JYsZMBEI8eA4pelwNWiZladrdc0Y7Ys2UOkjYZS544zL1z7tXkkXUfmZQTkvNw3cI9RAj4nkzaqNNej1uqyrV/Iz5J65Bw09JnnCycPa1Wvq6p9IBxivfP7QIz9VpP3HbmxZWkURiZaQDT35L1GTegxfQN1GRi5nf8AIQ1Kh5fUzWsrpsUW/ylzH6gW8pl+by1n9xUux+XDyBP5xKOupi+HEOBS5LILuv83FlimsHOBslm1l2FAmDK1PYuWOI2105uzFZjKXdVbBJCJ7wzKqjpMh+s15/rV07ZQY+Ui3CRGCnozOoDJR8',s:[0x1e0f5b6c08,0x04b7474658],u:'/cdn-cgi/challenge-platform/h/g'}})();</script></body>
</html>
